# Understanding Faiss

In [3]:
# Install Packages
!pip install faiss-cpu
!pip install sentence-transformers

In [4]:
# import pandas 
import pandas as pd 

In [5]:
df = pd.read_csv("FAISS_text.csv")

In [6]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [7]:
pip install sentence-transformers

Note: you may need to restart the kernel to use updated packages.


In [8]:
# Converting the text to vector using embeddings 

from sentence_transformers import SentenceTransformer

In [9]:
# Hugging face encoder 
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

In [10]:
vectors

array([[-0.00247395,  0.0362672 , -0.05290459, ..., -0.09152358,
        -0.0397    , -0.04330491],
       [-0.03357266,  0.00980515, -0.03250129, ..., -0.05165466,
         0.02245886, -0.03156183],
       [-0.01865324, -0.04051318, -0.01235387, ...,  0.00610584,
        -0.07179647,  0.02773853],
       ...,
       [-0.00066458,  0.0425213 , -0.05645508, ...,  0.01315471,
        -0.03183569, -0.04357664],
       [-0.03317154,  0.03252458, -0.0248484 , ...,  0.01174421,
         0.05747124,  0.00571022],
       [-0.00166394,  0.00413825, -0.04597083, ...,  0.02008527,
         0.05656242, -0.00161596]], dtype=float32)

In [11]:
vectors.shape

(8, 768)

In [12]:
vectors[0]

array([-2.47395458e-03,  3.62671986e-02, -5.29045872e-02, -2.17348468e-02,
        1.41723482e-02, -1.01601670e-03,  2.23637167e-02,  3.65196429e-02,
        3.80901322e-02,  5.22008399e-03, -3.00865509e-02,  2.05446221e-03,
        1.08503122e-02, -8.49087834e-02, -5.57267573e-03, -6.06597848e-02,
        2.32009729e-03, -1.51408855e-02,  1.20670693e-02,  1.98905468e-02,
       -1.27936434e-02, -2.72811279e-02, -3.31878439e-02,  3.40652163e-03,
        8.41168873e-03, -1.94854867e-02,  4.88132425e-02,  2.24118419e-02,
        4.53466848e-02, -5.90892211e-02, -9.13182274e-02, -1.22330664e-03,
       -4.05045748e-02,  8.67187232e-03,  1.26565260e-06, -1.92451179e-02,
       -3.20659205e-02, -4.08172347e-02,  8.79177377e-02, -1.52632445e-02,
        1.09908991e-02, -4.47977148e-02, -4.74823825e-03,  3.52632180e-02,
        1.31070651e-02,  1.09943897e-02, -3.45762656e-03,  9.12348703e-02,
        5.68809845e-02,  4.82893884e-02, -4.51438548e-03,  3.58451270e-02,
       -2.44210400e-02, -

In [13]:
dim = vectors.shape[1]

In [14]:
dim

768

In [15]:
import faiss
index = faiss.IndexFlatL2(dim)

In [16]:
index


<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x00000245035F26D0> >

In [17]:
index.add(vectors)

In [18]:
search_query = "An apple a day keeps doctor away"

In [19]:
vec = encoder.encode(search_query)

In [20]:
vec.shape

(768,)

In [21]:
import numpy as np 
svec = np.array(vec).reshape(1,-1)

In [22]:
svec.shape

(1, 768)

In [23]:
index.search(svec, k=2)

(array([[1.3908098, 1.7193402]], dtype=float32), array([[1, 0]], dtype=int64))

In [24]:
dis, I = index.search(svec, k=2)

In [25]:
dis

array([[1.3908098, 1.7193402]], dtype=float32)

In [26]:
I

array([[1, 0]], dtype=int64)

In [27]:
df.loc[I[0]]

text category
1  Fruits, whole grains and vegetables helps cont...   Health
0      Meditation and yoga can improve mental health   Health